dist: xenial
language: rust
cache: cargo
rust:
- stable
- beta
- nightly
addons:
  apt:
    packages:
      - texlive
      - libkpathsea6
      - libkpathsea-dev
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    cargo tarpaulin -v --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
